#!/usr/bin/env python

import RPi.GPIO as GPIO
from mfrc522 import SimpleMFRC522
from gpiozero import AngularServo
from time import sleep

servo = AngularServo(18, min_angle=-90, max_angle=90)

reader = SimpleMFRC522()

try:
        id, text = reader.read()
        print(id)
        print(text)
        servo.angle = 90
        sleep(5)

finally:
        servo.angle = 0
        GPIO.cleanup()
